version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  echoself-mcp:
    build: .
    ports:
      - "8086:8086"
    environment:
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_storage: